var annotated_dup =
[
    [ "Codigo", "class_codigo.html", "class_codigo" ],
    [ "Data", "class_data.html", "class_data" ],
    [ "Email", "class_email.html", "class_email" ],
    [ "Estado", "class_estado.html", "class_estado" ],
    [ "HistoriaDeUsuario", "class_historia_de_usuario.html", "class_historia_de_usuario" ],
    [ "IAA", "class_i_a_a.html", "class_i_a_a" ],
    [ "IAC", "class_i_a_c.html", "class_i_a_c" ],
    [ "IAP", "class_i_a_p.html", "class_i_a_p" ],
    [ "IDPE", "class_i_d_p_e.html", "class_i_d_p_e" ],
    [ "IDPR", "class_i_d_p_r.html", "class_i_d_p_r" ],
    [ "ISA", "class_i_s_a.html", "class_i_s_a" ],
    [ "ISC", "class_i_s_c.html", "class_i_s_c" ],
    [ "ISP", "class_i_s_p.html", "class_i_s_p" ],
    [ "MDPessoa", "class_m_d_pessoa.html", "class_m_d_pessoa" ],
    [ "MDProjeto", "class_m_d_projeto.html", "class_m_d_projeto" ],
    [ "MSA", "class_m_s_a.html", "class_m_s_a" ],
    [ "MSC", "class_m_s_c.html", "class_m_s_c" ],
    [ "MSP", "class_m_s_p.html", "class_m_s_p" ],
    [ "Nome", "class_nome.html", "class_nome" ],
    [ "Papel", "class_papel.html", "class_papel" ],
    [ "Pessoa", "class_pessoa.html", "class_pessoa" ],
    [ "PlanoDeSprint", "class_plano_de_sprint.html", "class_plano_de_sprint" ],
    [ "Prioridade", "class_prioridade.html", "class_prioridade" ],
    [ "Projeto", "class_projeto.html", "class_projeto" ],
    [ "Senha", "class_senha.html", "class_senha" ],
    [ "Tempo", "class_tempo.html", "class_tempo" ],
    [ "Texto", "class_texto.html", "class_texto" ]
];